#! /usr/bin/env php

<?php

require 'vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application('Laracasts Demo', '1.0');

$app->add(new Acme\RenderCommand);

$app->run();
